### ISSUE TITLE
TFMini PLus not macth with board nodemcu

### ISSUE THREAD

**Issue by Regaarya** [budryerson/TFMini-Plus-I2C#10]
hello bud, i use your code with board esp8622
its going well in arduino uno but not compitable with esp8266

problem when i verify this code for esp8266 is 

Arduino: 1.8.13 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\ASUS\AppData\Local\Temp\arduino_modified_sketch_654570\TFMP_example.ino:25:0:

C:\Users\ASUS\Documents\Arduino\libraries\printf/printf.h: In function 'void printf_begin()':

C:\Users\ASUS\Documents\Arduino\libraries\printf/printf.h:32:27: error: 'fdevopen' was not declared in this scope

 fdevopen( &serial_putc, 0 );

                           ^

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

maybe u can help me with this

**Comment by budryerson** [comment]
regaarya29,
I love to help; but I need more to go on.  Please send me info about the single board computer (SBC) that you are having trouble with (and the one that works), ALL of your sketch code, a text file of ALL your results and pictures (if you've got 'em) zipped into an archive.  Ideally, I will be able to duplicate the error and figure out where we went wrong.  Otherwise, we might be going back and forth for a long while.
Thanks,
Bud Ryerson
San Francisco
