### ISSUE TITLE
multiple TF sensors on a I2C Bus

### ISSUE THREAD

**Issue by mataoh92** [budryerson/TFMini-Plus-I2C#16]
Is there a way to use multiple TF sensors on a I2C Bus?

I think that the only way is to use a i2c multiplexer, because there's no pin to make the sensor shutdown nor any hardware pin to configure the sensor's slave address.

if there is a way, please let me know it.
thanks!

**Comment by budryerson** [comment]
"Is there a way to use multiple TF sensors on a I2C Bus?"
Yes. Connect the clock and data wires from each device to the same bus in parallel, and assign each device a different I2C address.  Be careful about cable length and proximity between the clock and data wires to avoid cross talk on the bus.

"I think that the only way is to use a i2c multiplexer"
 No.  That is not necessary.  I have never heard of an I2C multiplexer, but I don't know everything.

"there's no pin to make the sensor shutdown"
True; but the device will accept a command to start and stop sending data.  That command turns off the IR transmitter and puts the device into a low power state.

"nor any hardware pin to configure the sensor's slave address."
That's true; but I2C slave addresses are modified by a command.

I hope these answers are helpful.  Please let me know if you have any more questions.

Bud Ryerson
San Francisco

**Comment by mataoh92** [comment]
Thanks for your answer.

"Connect the clock and data wires from each device to the same bus in parallel, and assign each device a different I2C address."

-  when I try to assign each device a differenct address, will there be a collision because the two devices have a same address?

- and I think when I try to make the sensor shutdown by command, there will be a collision, even though I've tried it yet.

- for the case of VL53L1x ToF sensor, there is an external pin called SHUTDOWN which can be used to shutdown a device to assign an address to the other device on a same I2C bus. but this TF Luna sensor doesn't have.

- the above is that the reason why I think it's not possible to use multiple TF sensors on a I2C bus. if there is something I missed, please let me know.

**Comment by budryerson** [comment]
"when I try to assign each device a differenct address, will there be a collision because the two devices have a same address?"
Yes.  You have to change the I2C address one device at a time.

"and I think when I try to make the sensor shutdown by command, there will be a collision,"
No, not if they have different I2C addresses.

"for the case of VL53L1x ToF sensor, there is an external pin called SHUTDOWN which can be used to shutdown a device to assign an address to the other device on a same I2C bus. but this TF Luna sensor doesn't have."
Connect one TF-Luna. Change the address.  Connect a second.  Change the address.  Connect a third. Etc, etc.  Until all the TF-Lunas are connected and all the address are assigned.

"if there is something I missed, please let me know."
I do not understand your problem.  Maybe a picture or two of your setup would help me.

Finally, the TFLuna-I2C library is different than the TFMini-Plus-I2C library.  Please be sure that you use the correct library.

Good luck,

Bud

**Comment by mataoh92** [comment]
"Connect one TF-Luna. Change the address. Connect a second. Change the address. Connect a third. Etc, etc. Until all the TF-Lunas are connected and all the address are assigned."

- Now I understand what you said from the above sentence. thanks for your help.
